package com.nergal.hello.entities;

public enum Permission {
    NOTICE_READ,
    NOTICE_CREATE,
    NOTICE_UPDATE,
    NOTICE_DELETE,

    CONTRACT_READ,
    CONTRACT_CREATE,
    CONTRACT_UPDATE,
    CONTRACT_DELETE,

    ORDINANCE_READ,
    ORDINANCE_CREATE,
    ORDINANCE_UPDATE,
    ORDINANCE_DELETE,

    DECREE_READ,
    DECREE_CREATE,
    DECREE_UPDATE,
    DECREE_DELETE,

    LAW_READ,
    LAW_CREATE,
    LAW_UPDATE,
    LAW_DELETE,
}

